#!/usr/bin/env python3

import os
import copy
from rstool import algorithms
from rstool.postprocess import DEPS

if __name__ == '__main__':
	api = ''
	for name, obj in algorithms.__dict__.items():
		if name.startswith('calc_') and obj.__doc__ is not None:
			api += obj.__doc__.replace('\n\t', '\n')

	deps = ''
	for i, rec in enumerate(DEPS):
		target, source = rec[:2]
		newline = '' if i == len(DEPS) - 1 else '\\'
		deps += '%s 🠢 %s%s\n' % (
			', '.join(source) if isinstance(source, list) else source,
			', '.join(target) if isinstance(target, list) else target,
			newline,
		)

	with open('README.md.template') as f:
		doc = f.read()
	with open('README.md', 'w') as f:
		f.write(doc.format(api=api, deps=deps))
