#!/usr/bin/env python3

import os
import copy
from rstool import algorithms

if __name__ == '__main__':
	with open('README.md.template') as f:
		doc = f.read()
	api = ''
	for name, obj in algorithms.__dict__.items():
		if name.startswith('calc_') and obj.__doc__ is not None:
			api += obj.__doc__.replace('\n\t', '\n')
	with open('README.md', 'w') as f:
		f.write(doc.format(api=api))
